
CREATE DATABASE DBCRUDCORE;

USE DBCRUDCORE;

CREATE TABLE logins (
    id INT IDENTITY(1,1) PRIMARY KEY,
    Usuario NVARCHAR(50),
    Contraseña NVARCHAR(50)
);


CREATE TABLE Usuarios (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(100) NOT NULL,
    Fecha DATETIME NOT NULL,
    Clave NVARCHAR(50) NOT NULL
);